### ISSUE TITLE
Periodic eTRV commands

### ISSUE THREAD

**Issue by Achronite** [Achronite/mqtt-energenie-ener314rt#10]
This task is to investigate/implement a method periodic sending of messages for eTRVs due to the limitation of what the eTRV regularly reports/expects

Applicable Commands:

- DIAGNOSTICS - Every hour and/or when retries becomes 0 (for result of some commands)
- VOLTAGE - Maybe once a day
- EXERCISE_VALVE - Once a week

**Comment by Achronite** [comment]
Looks like VOLTAGE auto reports so is not needed for this:
```
...
energenie: monitor received={"deviceId":XXXX,"mfrId":4,"productId":3,"timestamp":1674211839,"TEMPERATURE":13.3,"command":0,"retries":0}
publishing energenie/3/XXXX/TEMPERATURE/state: 13.3
publishing energenie/3/XXXX/command/state: None
publishing energenie/3/XXXX/retries/state: 0
publishing energenie/3/XXXX/Maintenance/state: None
energenie: monitor received={"deviceId":XXXX,"mfrId":4,"productId":3,"timestamp":1674212149,"VOLTAGE":3.000000,"command":0,"retries":0,"VOLTAGE":3.00,"VOLTAGE_TS":1674212149}
publishing energenie/3/XXXX/VOLTAGE/state: 3
publishing energenie/3/XXXX/command/state: None
publishing energenie/3/XXXX/retries/state: 0
publishing energenie/3/XXXX/Maintenance/state: None
publishing energenie/3/XXXX/VOLTAGE_TS/state: 1674212149
```

**Comment by genestealer** [comment]
I did not know the voltage auto reports.

I created two automations for getting the voltage and calibrating the valve.

```
alias: Energenie eTRV Request Voltage Each Night
description: ""
trigger:
  - platform: time
    at: "04:00:00"
condition: []
action:
  - service: button.press
    data: {}
    target:
      entity_id:
        - button.5251_request_voltage
        - button.3449_request_voltage
        - button.5475_request_voltage
        - button.5318_request_voltage
        - button.office_heating_request_voltage
mode: single
```


```
alias: Energenie eTRV Calibrate Once a Week
description: ""
trigger:
  - platform: time
    at: "04:30:00"
condition:
  - condition: time
    weekday:
      - sun
action:
  - service: button.press
    data: {}
    target:
      entity_id:
        - button.5475_calibrate
        - button.5318_calibrate
        - button.5251_calibrate
        - button.3449_calibrate
        - button.office_heating_calibrate
mode: single
```
