### ISSUE TITLE
HA MQTT discovery - implement climate type for eTRV

### ISSUE THREAD

**Issue by Achronite** [Achronite/mqtt-energenie-ener314rt#16]
Created a separate issue for this as it is a little tricky to do. @djwillis

snip from #15 
----
It's been a while, but I think something like this would work (assuming that you infill a few vairables obviously), the shorter names will work of course.

The MQTT node/sensor discovery topic would be climate/..../climate and you would reuse a lot of the TARGET_TEMP (and that could also be left as a tempreture sensor I guess).

Fairly sure that this is close, BUT I have done it by butchering up the message for one of my TRV's. I'll check later and update.

{
"min_temp": 5,
"max_temp": 40,
"temp_step": 0.5, < Not sure if this is true for these TRVs
"temperature_state_topic": "~3/7575/TARGET_TEMP/state",
"temperature_state_template": "{{ value_json.value }}",
"temperature_command_topic": "~3/7575/TARGET_TEMP/command",
"device": {
"identifiers": [
"ener314rt-7575"
],
"name": "Radiator 7575",
"model": "Smart TRV",
"manufacturer": "mqtt-energenie-ener314rt",
"sw_version": "0.0.1"
},
"name": "Radiator 7575 climate",
"unique_id": "ener314rt-7575-CLIMATE"
}

**Comment by Achronite** [comment]
I've been testing. Example manual setup `configuration.yaml`:
```
  climate:
    - unique_id: Climate_Test
      name: "Climate Test"
      current_temperature_topic: "energenie/3/4280/TEMPERATURE/state"
      max_temp: 40
      min_temp: 5
      modes: ["auto","heat","off"]
      mode_command_topic: "energenie/3/4280/VALVE_STATE/command"
      mode_command_template: "{% if value == 'auto' %} Auto {% elif value == 'heat' %} Open {%- else %} Closed {% endif %}"
      temperature_command_topic: "energenie/3/4280/TARGET_TEMP/command"
      temperature_state_topic: "energenie/3/4280/TARGET_TEMP/state"
```
Is this everything we need?
