### ISSUE TITLE
Implement 'last_seen' topic for OpenThings devices

### ISSUE THREAD

**Issue by Achronite** [Achronite/mqtt-energenie-ener314rt#18]
As mentioned in #16.

Translate the timestamp value returned by FSK/OpenThings devices into an ISO timestamp and publish as a 'last_seen' topic, similar to Zigbee2Mqtt, for the device.  e.g. `energenie/3/4280/last_seen/state

**Comment by djwillis** [comment]
Sounds like a great idea, could you consider adding some sort of availability flag (online/offline) at the same time? Mind you, I feel rather like I am just commenting to say 'one more thing' all the time ;-).

For my messing with the eTRV's I am deriving it from the epoch timestamp for VOLTAGE_TS and setting it to online if less than 90 mins ago, offline if over 90 mins ago (fairly sure that I am wrong to be using that state due to when it is reported).

It's a hack and I am just doing it for testing while trying to optimise the setup for the climate device. 

If you add the last_seen state for FSK it could easily be derived from that. 

The retained topics for the TRV also make the online/offline state a tiny bit more relevant in that case than the other FSK devices as they are far more frequently polling anyway so offline is more likely to indicate orphaned or unplugged.

**Comment by Achronite** [comment]
It is working better if i convert to an ISO8601 time string (e.g. `2023-01-29T19:57:15.000Z`) in the application and then set the type as 'timestamp' in HA.  HA then works out how long ago that actually was, for example:...
```
mqtt
  sensor:
    - unique_id: 4870_lastseen
      name: "Radiator 4280 Last seen"
      state_topic: energenie/3/4280/last_seen/state
      device_class: timestamp
    - unique_id: 14736_lastseen
      name: "House Energy 14736 Last seen"
      state_topic: energenie/5/14736/last_seen/state
      device_class: timestamp
```
Gives:
![image](https://user-images.githubusercontent.com/10363609/215353129-6fe522cd-f457-47c5-8141-963e1e7bac84.png)


I think it might be worth adding the last_seen to MQTT discovery on this basis.

**Comment by Achronite** [comment]
I think I'm going to leave the MQTT states for the timestamps as epochs.  I've managed to work out the correct formatting to use in Home Assistant to convert the epoch to a HA timestamp, which effectively does the same as above.

Using VALVE_TS as an example manual MQTT entity:
```
mqtt:
  sensor:
    - unique_id: 4870_valvets
      name: "Radiator 4280 Valve TS"
      state_topic: energenie/3/4280/VALVE_TS/state
      value_template: "{{ as_datetime(value).isoformat() }}"
      device_class: timestamp
```
