### ISSUE TITLE
Enhance Readme with Device Registry Best Practices

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#75]
### UPDATE

I was wrong on one point. "Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to `null` as a work-a-round to avoid a duplicate name." "This stops working in version 2024.2.0. Please address before upgrading."  

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/2d5fd155-a041-4314-9c54-0b27740dc477)

I have updated the examples to reflect the same naming as we have in the MQTT discovery, I have avoided using `null`.

## Description

I'd like to propose a modification to the readme to better align with Home Assistant's [Device Registry](https://developers.home-assistant.io/docs/device_registry_index/) behavior. The current example might lead to unexpected results due to inconsistencies in device grouping.

## Issue

- The readme example attempts to group multiple entities under a single device. However, each device in Home Assistant should ideally represent a distinct physical device, with its own unique set of attributes (name, model, etc.).
- Grouping entities under a single device can result in Home Assistant adopting the attributes of the first entity for all subsequent entities, as highlighted in the examples below.

## Suggestion

- Adjust the readme example to demonstrate device configuration that adheres to best practices, ensuring each device has its own unique attributes.
- Provide clear guidance on how to:
  - Configure devices with multiple entities (e.g., a light switch with multiple buttons).
  - Employ the identifiers property for proper device linking.
  - Use the name property appropriately to ensure device visibility in the Device Registry.

## Issue Example
See the example below for that happens if different entities are attempted to be "grouped" under one device.
Results in the "issue", where the first entities device settings are taken as ther master version for all following entities 

``` YAML
mqtt:
  light:
    - name: "Lounge Light Switch"
      unique_id: MIHO008_light1
      command_topic: energenie/ook/87/1/command
      optimistic: true
      state_topic: energenie/ook/87/1/state
      availability_topic: energenie/availability/state
      device:
        name: "Energenie OOK"
        identifiers: "ook"
        model: "2-Gang Light Switch (MIHO009)"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"

  switch:
    - name: "Coffee Maker"
      unique_id: ENER002_socket
      command_topic: energenie/ook/89/1/command
      optimistic: true
      state_topic: energenie/ook/89/1/state
      availability_topic: energenie/availability/state
      device:
        name: "Energenie OOK"
        identifiers: "ook"
        model: "Smart Plug (MIHO002)"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"

    - name: "Subwoofer"
      unique_id: ENER010_socket_2
      command_topic: energenie/ook/564/2/command
      optimistic: true
      state_topic: energenie/ook/564/2/state
      availability_topic: energenie/availability/state
      device:
        name: "Energenie OOK"
        identifiers: "ook-4gang"
        model: "4-Gang (ENER010)"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"
```
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/65d3c70c-356f-42d0-be69-9d7556f280ff)
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/0ab90c97-d81f-486b-a804-1704788a23bc)

## Suggested Fix

> [!IMPORTANT]  
> `name` is repeated. Omitting the first `name` / setting it to `null` will mean the device will not show in the `device registry` (xxx/devices/dashboard). Omitting the second `name` will result in the device being listed in the `device registry` with the IP address of the MQTT broker as a prefix.

### For single devices, e.g. A light with only On/Off:

> [!NOTE]  
> The two name's do not have to match. E.G. You could have the first `name` set to `temperature` and the second `name` set to `Radiator`

```YAML
mqtt:
  light:
    - name: "Light"
      unique_id: MIHO009_light_hallway_up
      command_topic: energenie/ook/87/1/command
      optimistic: true
      state_topic: energenie/ook/87/1/state
      availability_topic: energenie/availability/state
      device:
        name: "Upstairs Hallway"
        identifiers: "miho009_light_hallway_up"
        model: "2-Gang Light Switch (MIHO009) [87/1]"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"
        suggested_area: "Hallway"
```
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/3bf37aab-f179-4984-ba11-b197840adeec)

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/3cbb0c81-2c51-4e00-a277-e0d7ba01b356)

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/6c552d01-da97-4708-b338-dedc1abc8ea2)

### Example of device with multiple entities:

> [!TIP]  
> On the second entity, only the identifier is required in the device registry, as Home Assistant will link the two entities together into one device.
   
```YAML
mqtt:
  light:
    - name: "Light"
      unique_id: MIHO009_light_hallway_up
      command_topic: energenie/ook/87/1/command
      optimistic: true
      state_topic: energenie/ook/87/1/state
      availability_topic: energenie/availability/state
      device:
        name: "Hallway"
        identifiers: "miho009_light_hallway"
        model: "2-Gang Light Switch (MIHO009) [87/1]"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"
        suggested_area: "Hallway"

    - name: "Light"
      unique_id: MIHO009_light_hallway_down
      command_topic: energenie/ook/87/2/command
      optimistic: true
      state_topic: energenie/ook/87/2/state
      availability_topic: energenie/availability/state
      device:
        identifiers: "miho009_light_hallway"



```
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/9c681a82-f761-4920-8603-c773bf827010)

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/cee726a5-ff7e-4aac-9813-c823d33ed746)

### Examples
```YAML
mqtt:
  light:
    - name: "Light"
      unique_id: MIHO008_light_bedroom
      command_topic: energenie/ook/600/1/command
      optimistic: true
      state_topic: energenie/ook/600/1/state
      availability_topic: energenie/availability/state
      device:
        name: "Bedroom Ceiling"
        identifiers: "miho008_light_bedroom"
        model: "Light Switch (MIHO008) [600/1]"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"
        suggested_area: "Bedroom"

    - name: "Light"
      unique_id: MIHO010_Dimmer1
      command_topic: energenie/ook/669/dimmer/command
      optimistic: false
      state_topic: energenie/ook/669/dimmer/state
      state_value_template: "{{ 'OFF' if value == 'OFF' else 'ON' }}"
      brightness_state_topic: energenie/ook/669/dimmer/state
      brightness_command_topic: energenie/ook/669/dimmer/command
      brightness_scale: 10
      payload_on: 'ON'
      payload_off: 'OFF'
      on_command_type: "brightness"
      availability_topic: energenie/availability/state
      device:
        name: "Kitchen Dimmer"
        identifiers: "MIHO010_Dimmer1"
        model: "Dimmer Switch (MIHO010) [669]"
        manufacturer: "energenie"
        via_device: "mqtt-ener314rt"

  
  switch:
    - name: "Switch"
      unique_id: MIHO002_socket1
      command_topic: energenie/ook/697441/2/command
      optimistic: true
      state_topic: energenie/ook/697441/2/state
      availability_topic: energenie/availability/state
      device:
        name: "TV Speakers"
        identifiers: "miho002_socket1"
        model: "Smart Plug (MIHO002) [697441/2] (Button 2)"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"

    - name: "Switch"
      unique_id: MIHO002_socket2
      command_topic: energenie/ook/697441/3/command
      optimistic: true
      state_topic: energenie/ook/697441/3/state
      availability_topic: energenie/availability/state
      device:
        name: "Laptop Power"
        identifiers: "miho002_socket2"
        model: "Smart Plug (MIHO002) [697441/3] (Button 3)"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"

    - name: "Switch"
      unique_id: ENER010_socket_2
      command_topic: energenie/ook/564/2/command
      optimistic: true
      state_topic: energenie/ook/564/2/state
      availability_topic: energenie/availability/state
      device:
        name: "Subwoofer"
        identifiers: "ener010_socket_2"
        model: "4-Gang (ENER010) [564/2]"
        manufacturer: "Energenie"
        via_device: "mqtt-ener314rt"

```

**Comment by Achronite** [comment]
How about this, the devices are split by OOK zone code?

This would mean that if you have a 4-way gang or double socket/switch they would share the same device entry, and this should only be defined once.  So something like:
```
  - unique_id: subwoofer
    name: "Subwoofer"
    command_topic: energenie/ook/8887/1/command
    optimistic: false
    state_topic: energenie/ook/8887/1/state
    availability_topic: energenie/availability/state
    device:
      name: "energenie 4 gang"
      identifiers: ["ook-8887"]
      model: "4 Way Extension Lead [8887]"
      manufacturer: "energenie"
      via_device: "mqtt-ener314rt"
  - unique_id: fountain
    name: "Fountain"
    command_topic: energenie/ook/8887/4/command
    optimistic: false
    state_topic: energenie/ook/8887/4/state
    availability_topic: energenie/availability/state
    device:
      identifiers: ["ook-8887"]
```
Similarly you could group devices together if you use the same zone; this could possibly allow for switch 0 (all in zone) switching too; providing I can come up with a good way to dealing with the multiple states...
