### ISSUE TITLE
Add dropdown to climate control dashboard card for most used maintainance operations

### ISSUE THREAD

**Issue by Achronite** [Achronite/mqtt-energenie-ener314rt#90]
Release 2023.9 of Home Assistant introduced option [features](https://www.home-assistant.io/dashboards/features/) that can be added to dashboard cards.  This change would make use of a drop-down to add some of the maintenance commands for the eTRV as an option entry.

Something along these lines:

```
features:
  - type: climate-preset-modes
    style: dropdown
    preset_modes:
      - "Cancel Command"
      - "Request Diagnostics"
      - "Request Voltage"
      - "Exercise Valve"
      - "Identify"
      - "Low Power Mode ON"
      - "Low Power Mode OFF"
```
